# The below yml file is for local dev 
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   storageClassName: mylocalstorage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: mylocalstorage
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/mongo-storage-new"
#     type: DirectoryOrCreate

# The below yml files is for AWS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---

apiVersion: storage.k8s.io/v1
kind:  StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2